const CARD_CREATE = "CARD_CREATE";
const CARD_REMOVE = "CARD_REMOVE";
const BOARD_CREATE = "BOARD_CREATE";
const BOARD_REMOVE = "BOARD_REMOVE";

export { CARD_CREATE, CARD_REMOVE, BOARD_CREATE, BOARD_REMOVE };
